{"uuid":"2f513050-00ed-462c-a60f-dd0843620a7f","historyId":"2e79d5b55bba9b56cb9170b0bbb1832a","fullName":"AwaitilityTests.waitUntilAsserted","labels":[{"name":"package","value":"AwaitilityTests"},{"name":"testClass","value":"AwaitilityTests"},{"name":"testMethod","value":"waitUntilAsserted"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"rest-assured-testng-framework"},{"name":"subSuite","value":"AwaitilityTests"},{"name":"host","value":"DESKTOP-GDSL4V8"},{"name":"thread","value":"29580@DESKTOP-GDSL4V8.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"waitUntilAsserted","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Condition with alias 'My custom message' didn't complete within 5 seconds because assertion condition defined as a Lambda expression in AwaitilityTests null.","trace":"org.awaitility.core.ConditionTimeoutException: Condition with alias 'My custom message' didn't complete within 5 seconds because assertion condition defined as a Lambda expression in AwaitilityTests null.\r\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)\r\n\tat org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)\r\n\tat org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)\r\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)\r\n\tat org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)\r\n\tat AwaitilityTests.waitUntilAsserted(AwaitilityTests.java:18)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)\r\n\tat org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)\r\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)\r\n\t... 30 more\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"Request","source":"682b3235-5c85-4f2b-82c2-5844a6ccbb06-attachment.html","type":"text/html"}],"parameters":[],"start":1747151689765,"stop":1747151698581}